### ISSUE TITLE
Click event for add is exponential :/

### ISSUE THREAD

**Issue by luketlancaster** [nss-evening-cohort-12/firebase-mushrooms#12]
<img width="1552" alt="Screen Shot 2020-07-06 at 9 27 14 PM" src="https://user-images.githubusercontent.com/8376505/86692642-92c8f380-bfcf-11ea-89e1-9001babfdc9e.png">

when creating the second mushroom, 2 get created. Multiple click events firing?

**Comment by michaelclark2** [comment]
apparently you can use this jquery function instead of `on`  
https://api.jquery.com/one/

**Comment by nswalters** [comment]
@TheDotson This was the bug you were seeing. 😄
